#!/usr/bin/python

from email.mime.text import MIMEText
import os.path
import smtplib

from portal_changedetect_config import COMMIT_LOGS, PORTAL_NAME

#PORTAL_NAME = 'something'
#COMMIT_LOGS = ('/Users/jaclu/proj/europeana/trunk/portal2/src/main/resources/message_keys/webcommiters.log',
#                '/Users/jaclu/proj/europeana/trunk/staticpages2/webcommiters.log',
#                )

for commit_log in COMMIT_LOGS:
    ddir, fname = os.path.split(commit_log)
    hist_fname = os.path.join(ddir, 'commit_history')
    try:
        last_change = open(hist_fname,'r').read()
    except:
        last_change = ''
        
    commit_time, commiter = open(commit_log).readlines()[-1].strip().rsplit(' ',1)
    if commit_time == last_change:
        # no change picked up
        continue
    print 'Change found in %s' % commit_log
    
    fromaddr = PORTAL_NAME.strip()
    body = 'New content deployed in %s\nCommited by you arround %s\nPortal should pick it up within 5 mins' % (ddir, commit_time)
    msg = MIMEText(body)
    msg['From'] = fromaddr
    msg['To'] = commiter
    msg['Subject'] = 'Portal has recieved multilingo content'    
    try:
        smtpObj = smtplib.SMTP('localhost')
        smtpObj.sendmail(fromaddr, commiter, msg.as_string())        
        print "Successfully sent email"
    except smtplib.SMTPException:
        print "Error: unable to send email"
        continue
    open(hist_fname,'w').write(commit_time)
    
